### PR TITLE
Fix box buyin count update

### LINKED ISSUE #90: Box buy-in adds count to ALL products instead of box product
Possibly caused by update query missing where statement.
https://github.com/TKOaly/rv-backend/blob/57930f7fd0ac626ace01850118379d6bfee8417d/src/db/boxStore.js#L223-L226

### PR DESCRIPTION
**Pull request by ArktinenKarpalo**

### CODE REVIEW

File: src/db/boxStore.js [hunk 1]
```diff
@@ -198,20 +198,26 @@ module.exports.buyIn = async (boxBarcode, boxCount) => {
...
         }
 
-        const { count, itemcount, priceid } = row;
+        const { count, itemcount, priceid, barcode } = row;
 
         const newCount = count + itemcount * boxCount;
 
         await knex('PRICE')
             .transacting(trx)
             .select({ priceid, endtime: null })
```
Comment (Jokauppi) [inline src/db/boxStore.js]: I think this select can be removed? Nothing is returned.

Edit: Is this actually filtering anything or am I missing something? This type of .select({}) syntax is not found in any Knex docs

File: src/db/boxStore.js [hunk 2]
```diff
@@ -198,20 +198,26 @@ module.exports.buyIn = async (boxBarcode, boxCount) => {
...
-            .update({ count: newCount });
+            .update({ count: newCount })
+            .where('PRICE.barcode', barcode);
```
Comment (Jokauppi) [inline src/db/boxStore.js]: This could have updated the count of some previous price if the select above doesn't do anything.
Should be:
```javascript
.where({ barcode: barcode, endtime: null })
```

**Review by Jokauppi — CHANGES_REQUESTED** [review]

File: src/db/boxStore.js (hunk 2 above)
Comment (ArktinenKarpalo) [reply src/db/boxStore.js]: see previous conversation

File: src/db/boxStore.js (hunk 1 above)
Comment (ArktinenKarpalo) [reply src/db/boxStore.js]: Actually yes it could be that select is supposed to be where, and instead of where barcode, where priceid should be used to limit the query. I don't know if priceid is unique (edit: seems to be) or not or why endtime: null is there.

Comment (ArktinenKarpalo) [reply src/db/boxStore.js]: Could be argued that the current concept of price table is confusing and should be refactored to separate price table with only the current price and then another with price history or something like this. Especially having count column even in historical prices is very confusing. What is count of some product price that is no longer relevant? Lots of unwritten rules that you have to dig source code through to figure out.

Comment (Jokauppi) [reply src/db/boxStore.js]: > I don't know if priceid is unique (edit: seems to be) or not or why endtime: null is there.

Now looking at this where-ing with the priceid wouldn't work with the current query as it joins to any (previous) price and may not match the last one that's not null. `{ barcode, endtime: null }` always resolves to the correct one but `{ priceid }` only if the query above has `.where({ endtime: null })`

I thought at first the price table was just for recording price history but apparently not. I was wondering why products weren't being sold according to their batch price but this table was for doing exactly that. I think we should implement the way it was in the old RV. Doesn't seem like it would impact any current endpoints apart from /purchase.
